// This file is auto-generated by @hey-api/openapi-ts

export { createProduct, getProductById, getProducts, type Options } from './sdk.gen';
export type { ClientOptions, CreateProductData, CreateProductError, CreateProductErrors, CreateProductResponse, CreateProductResponses, GetProductByIdData, GetProductByIdError, GetProductByIdErrors, GetProductByIdResponse, GetProductByIdResponses, GetProductsData, GetProductsResponse, GetProductsResponses } from './types.gen';
