// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:4000' | (string & {});
};

export type GetProductsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/products';
};

export type GetProductsResponses = {
    /**
     * List of products
     */
    200: Array<{
        id: number;
        name: string;
        description: string;
        price: string;
        stock: number;
        category: string;
    }>;
};

export type GetProductsResponse = GetProductsResponses[keyof GetProductsResponses];

export type CreateProductData = {
    /**
     * Product data
     */
    body: {
        name: string;
        description: string;
        /**
         * Decimal number format
         */
        price: string | number;
        stock: number;
        category: string;
    };
    path?: never;
    query?: never;
    url: '/products';
};

export type CreateProductErrors = {
    /**
     * Validation error
     */
    422: {
        code: string;
        message: string;
        issues: Array<{
            code: 'custom' | 'invalid_type' | 'unrecognized_keys' | 'invalid_union' | 'too_big' | 'too_small' | 'invalid_format' | 'not_multiple_of' | 'invalid_key' | 'invalid_element' | 'invalid_value';
            path: Array<string | number>;
            message: string;
        }>;
    };
};

export type CreateProductError = CreateProductErrors[keyof CreateProductErrors];

export type CreateProductResponses = {
    /**
     * Product created
     */
    201: {
        id: number;
        name: string;
        description: string;
        price: string;
        stock: number;
        category: string;
    };
};

export type CreateProductResponse = CreateProductResponses[keyof CreateProductResponses];

export type GetProductByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/products/{id}';
};

export type GetProductByIdErrors = {
    /**
     * Product not found
     */
    404: {
        code: string;
        message: string;
    };
};

export type GetProductByIdError = GetProductByIdErrors[keyof GetProductByIdErrors];

export type GetProductByIdResponses = {
    /**
     * Product found
     */
    200: {
        id: number;
        name: string;
        description: string;
        price: string;
        stock: number;
        category: string;
    };
};

export type GetProductByIdResponse = GetProductByIdResponses[keyof GetProductByIdResponses];
