// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/vue-query';

import { client } from '../client.gen';
import { createProduct, getProductById, getProducts, type Options } from '../sdk.gen';
import type { CreateProductData, CreateProductError, CreateProductResponse, GetProductByIdData, GetProductByIdError, GetProductByIdResponse, GetProductsData, GetProductsResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getProductsQueryKey = (options?: Options<GetProductsData>) => createQueryKey('getProducts', options);

/**
 * Get all products
 *
 * Retrieve a list of all available products
 */
export const getProductsOptions = (options?: Options<GetProductsData>) => queryOptions<GetProductsResponse, DefaultError, GetProductsResponse, ReturnType<typeof getProductsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getProducts({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getProductsQueryKey(options)
});

/**
 * Create a product
 *
 * Create a new product
 */
export const createProductMutation = (options?: Partial<Options<CreateProductData>>): UseMutationOptions<CreateProductResponse, CreateProductError, Options<CreateProductData>> => {
    const mutationOptions: UseMutationOptions<CreateProductResponse, CreateProductError, Options<CreateProductData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createProduct({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getProductByIdQueryKey = (options: Options<GetProductByIdData>) => createQueryKey('getProductById', options);

/**
 * Get product by ID
 *
 * Retrieve a single product by its ID
 */
export const getProductByIdOptions = (options: Options<GetProductByIdData>) => queryOptions<GetProductByIdResponse, GetProductByIdError, GetProductByIdResponse, ReturnType<typeof getProductByIdQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getProductById({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getProductByIdQueryKey(options)
});
