import '@tanstack/vue-query'

/** User-defined domain keys */
type AppQueryKey = ['auth-session', ...ReadonlyArray<unknown>]

/** Keys auto-generated by @hey-api/openapi-ts (object with _id) */
type GeneratedQueryKey = [{ _id: string } & Record<string, unknown>]

type QueryKey = AppQueryKey | GeneratedQueryKey

declare module '@tanstack/vue-query' {
  // eslint-disable-next-line no-unused-vars
  interface Register {
    queryKey: QueryKey
    mutationKey: QueryKey
  }
}
