// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config'
import { defineConfig } from 'prisma/config'
import env from './src/env.js'

export default defineConfig({
  schema: 'src/core/db/prisma/schema.prisma',
  migrations: {
    path: 'src/core/db/prisma/migrations',
  },
  datasource: {
    url: env.DB_URL,
  },
})
